name = "CZI"
uuid = "3945b127-b976-4324-94b4-ee8d09e47738"
version = "1.0.0-DEV"
authors = ["Eric Skaliks"]

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
ImageAxes = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
libczi_julia_jll = "b7f83724-4c17-5efb-a12f-5857ac4eb200"

[compat]
ColorTypes = "0.12.1"
CxxWrap = "0.17.4"
Dates = "1.11.0"
EzXML = "1.2.3"
ImageAxes = "0.6.12"
ImageIO = "0.6.9"
ImageTransformations = "0.10.2"
Images = "0.26.2"
PlutoLinks = "0.1.6"
PlutoUI = "0.7.76"
UUIDs = "1.11.0"
Unitful = "1.27.0"
julia = "1.6.7"
libczi_julia_jll = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
